### ISSUE TITLE
Create new endpoint that provides the underlying Kubernetes Deployment

### ISSUE THREAD

**Issue by olis1996** [DataCater/datacater#195]
Create a new endpoint that provides the underlying Kubernetes Deployment. This might be helpful to, for instance, investigate how many replicas of the Kubernetes Deployment are available. 

This issue needs some conceptional work, so please feel free to share your thoughts in the comments

**Comment by HknLof** [comment]
Quick drawing of the desired process:

<img width="1564" alt="Screenshot 2023-03-23 at 10 34 47" src="https://user-images.githubusercontent.com/4265969/227162225-74e87816-e76b-4563-8289-4ffa9b46143b.png">


Response of `kubectl get deploy core-dns -n kube-system` from a local minikube:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
...
spec:
...
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-01-12T10:37:00Z"
    lastUpdateTime: "2023-01-12T10:37:00Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-01-12T10:35:19Z"
    lastUpdateTime: "2023-01-12T10:37:03Z"
    message: ReplicaSet "coredns-b4854dd98" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2

```
